import csv
import os
import shutil
import subprocess
from pathlib import Path

from genome2vec.transformer_tools import split_to_max_length


def annotate_genome(fasta_path: Path, bakta_db_path: str, threads: int):
    """
    Run Bakta annotation on a single fasta file

    Parameters
    ----------
    fasta_path : Path
        Path to fasta assembly file to be annotated

    threads : int
        Number of threads to run the annotation on

    Returns
    -------
    annotation_table_path
        Path to gff3 file generated by Bakta
    """
    # TODO: catch bakta output for logger
    bakta_db = Path(bakta_db_path)
    annotation_output_dir = os.path.dirname(fasta_path).replace(
        'genome_sequences', 'genome_annotations')
    sample = fasta_path.stem
    annotation_table_path = os.path.join(annotation_output_dir, f"{sample}.gff3")

    # exit function if annotation has already been completed
    if os.path.exists(annotation_table_path):
        return annotation_table_path

    # otherwise annotate
    os.makedirs(annotation_output_dir, exist_ok=True)
    cmd = [
        "bakta",
        "--db", str(bakta_db),
        "--output", str(os.path.join(annotation_output_dir, sample)),
        "--threads", str(threads),
        str(fasta_path),
        "--force"
    ]
    # logic for subprocess to catch errors
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr)

    # move gff3 file to annotation output dir, delete other files
    bakta_output_dir = os.path.join(annotation_output_dir, sample)
    bakta_annotation_output = os.path.join(bakta_output_dir, f"{sample}.gff3")
    shutil.move(bakta_annotation_output, annotation_table_path)
    shutil.rmtree(bakta_output_dir)

    return annotation_table_path


def split_sequence_for_tokenizer(
        annotation_table_path: str, fasta_path: str, max_length: int) -> list:
    """
    Use annotation table and contigs in fasta to extract

    Parameters
    ----------
    annotation_table_path : str
        Annotations of the sequence.
    fasta_path : str
        As named
    max_length : int
        Maximum length (in characters) of each chunk. Choose this to match the tokenizer's
        maximum input size (or slightly smaller).

    Returns
    -------
    List[str]
        List of sequence segments suitable for chunking and passing to the model.
    """
    if max_length <= 0:
        raise ValueError("max_length must be > 0")

    genome = parse_fasta(fasta_path)
    contig_map = {f"contig_{i+1}": key for i, key in enumerate(genome)}
    ordered_segments = []

    # read gff file line-by-line
    with open(annotation_table_path, 'r') as f:
        reader = csv.reader(f, delimiter='\t')

        for row in reader:

            # stop when the FASTA section begins (for gff3 tables)
            if row == ["##FASTA"]:
                return ordered_segments

            # skip comments, metadata, or incomplete rows
            if not row or row[0].startswith('#'):
                continue

            seqid = row[0]
            feature_type = row[2]
            # gff table indexing is 1-based inclusive, subtract 1 from start to convert to Python
            # 0-based indexing.
            start = int(row[3]) - 1
            end = int(row[4])
            strand = row[6]

            # get contig id of fasta that matches row in annotation table
            # First try your existing substring match
            contig_id = next((key for key in genome if key in seqid), None)

            # If that fails, try the contig_N mapping
            if contig_id is None:
                contig_id = contig_map.get(seqid)

            if feature_type in {"region", "gap"}:
                continue

            # extract sequence from contig
            segment = genome[contig_id][start:end]

            # Handle negative strand orientation
            if strand == '-':
                segment = reverse_complement(segment)

            # split into chunks that the model can handle
            chunk_list = split_to_max_length(segment, max_length)
            ordered_segments.append(chunk_list)

    return ordered_segments


def parse_fasta(fasta_path: str) -> dict:
    """Parses a FASTA file into a {seqid: sequence} dictionary."""
    sequences = {}
    current_id = None
    current_seq = []

    with open(fasta_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith('>'):
                if current_id:
                    sequences[current_id] = "".join(current_seq)
                # Take the first word of the header as the sequence ID
                current_id = line[1:].split()[0]
                current_seq = []
            else:
                current_seq.append(line.upper())

        if current_id:
            sequences[current_id] = "".join(current_seq)

    return sequences


def reverse_complement(dna_seq: str) -> str:
    """Computes the reverse complement using Python's built-in str.translate."""
    trans = str.maketrans("ATGCatgcNn", "TACGtacgNn")
    return dna_seq.translate(trans)[::-1]
